load("@aspect_gazelle_prebuilt//:def.bzl", "aspect_gazelle")
load("@aspect_rules_lint//format:defs.bzl", "format_multirun")
load("@aspect_rules_ts//ts:defs.bzl", "ts_config")
load("@bazel_env.bzl", "bazel_env")
load("@multitool//:tools.bzl", multitool_tools = "TOOLS")
load("@npm//:defs.bzl", "npm_link_all_packages")

bazel_env(
    name = "bazel_env",
    toolchains = {
        "nodejs": "@nodejs_toolchains//:resolved_toolchain",
    },
    tools = {
        "node": "$(NODE_PATH)",
        "pnpm": "@pnpm//:pnpm",
    } | multitool_tools,
)

format_multirun(
    name = "format",
    starlark = "@buildifier_prebuilt//:buildifier",
)

# Enumerate all relevant gazelle directives for learning/reference (some may repeat default values)
# gazelle:exclude **/.*.gen.*
# gazelle:alias_kind ts_library ts_project
# gazelle:js enabled
# gazelle:js_tsconfig enabled
# gazelle:js_proto disabled
# gazelle:js_npm_package disabled
# gazelle:js_tsconfig_ignore allow_js
# gazelle:js_tsconfig_ignore preserve_jsx
# gazelle:js_validate_import_statements error
# gazelle:map_kind ts_project ts_library //:ts_library.bzl
# gazelle:js_project_naming_convention main
# gazelle:js_tests_naming_convention test
# gazelle:js_files **/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts}
aspect_gazelle(
    name = "gazelle",
    languages = ["js"],
)

npm_link_all_packages(name = "node_modules")

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
    visibility = ["//visibility:public"],
)
