load("@aspect_rules_lint//format:defs.bzl", "format_multirun")
load("@gazelle//:def.bzl", "gazelle")
load("@rules_typescript//ts:defs.bzl", "ts_refresh_tsconfig")

package(default_visibility = ["//visibility:public"])

# Root config files that any package can use
exports_files([
    "oxlint.json",
])

# Configure Gazelle
# gazelle:ts_package_boundary every-dir
# gazelle:go_naming_convention import
# gazelle:exclude .config
# gazelle:exclude common/hosting.api
# gazelle:exclude domains/example.api
# gazelle:exclude global.json

gazelle(
    name = "gazelle",
    args = ["-go_naming_convention=import"],
    gazelle = "@rules_typescript//gazelle:gazelle_ts",
)

ts_refresh_tsconfig(name = "refresh_tsconfig")

filegroup(
    name = "starlark_files",
    srcs = glob(
        [
            "**/*.bzl",
            "**/BUILD.bazel",
        ],
        allow_empty = True,
        exclude = [
            ".cache/**",
            "artifacts/**",
        ],
    ) + [
        "MODULE.bazel",
        "REPO.bazel",
        "WORKSPACE.bazel",
    ],
)

alias(
    name = "lint",
    actual = "//tools/lint:lint",
)

format_multirun(
    name = "format",
    css = "//tools/format:prettier",
    go = "@aspect_rules_lint//format:gofumpt",
    html = "//tools/format:prettier",
    javascript = "//tools/format:oxfmt",
    markdown = "//tools/format:prettier",
    starlark = "@buildifier_prebuilt//:buildifier",
)
