packages: [] # Single root package.json

catalog:
  '@tanstack/react-router': 1.170.5
  '@tanstack/react-start': 1.168.7
  '@tanstack/router-cli': 1.167.4
  '@types/node': 25.9.1
  '@types/react': 19.2.15
  '@types/react-dom': 19.2.3
  '@vitejs/plugin-react': 6.0.2
  oxfmt: 0.51.0
  react: 19.2.6
  react-dom: 19.2.6
  typescript: 6.0.3
  vite: 8.0.13
  vite-tsconfig-paths: 7.0.0-alpha.1

overrides:
  # Can be removed once <https://github.com/cheeriojs/cheerio/pull/5157> merges
  encoding-sniffer: 1.0.2

  # Override v6 dependency (v7 was min Node.js breaking only)
  semver: 7.8.0

## Bazel-driven configuration
autoInstallPeers: false # Ensure peer deps exist in package.json
strictPeerDependencies: true # Ensure peer deps exist in package.json
resolvePeersFromWorkspaceRoot: false # For hermeticity
hoist: false # rules_js requirement <https://docs.aspect.build/bazel/javascript#package-management-with-pnpm>
pmOnFail: ignore # Bazel manages pnpm, so ignore the check
savePrefix: "" # Pin to exact versions
extendNodePath: false # For hermeticity

## Catalog configuration
catalogMode: strict
cleanupUnusedCatalogs: true

## Supply chain security
allowBuilds:
  __bazel_needs_allowBuilds_do_not_delete__: false
minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true
trustPolicy: no-downgrade
ignoreScripts: true

## Other
updateNotifier: false # Defer to dependency update process
