# TODO: AI: Why is `cmd` in the directory path? That seems unneeded.
load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_binary(
    name = "tasksapi",
    embed = [":go_default_library"],
    # TODO: AI: Is this import path the standard for INTERNAL imports? If not, make changes (throughout).
    importpath = "github.com/connorjs/tasks.how/domains/tasks.api/cmd/tasksapi",
    visibility = ["//visibility:public"],
)

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = "github.com/connorjs/tasks.how/domains/tasks.api/cmd/tasksapi",
    visibility = ["//visibility:private"],
    deps = [
        "//domains/tasks.api/hello:go_default_library",
        "@com_github_go_chi_chi_v5//:go_default_library",
    ],
)
