load("//:ts_library.bzl", "ts_library")

ts_library(
    name = "main",
    srcs = ["router.ts"],
    declaration = True,
    emit_declaration_only = True,
    tsconfig = "//:tsconfig",
    visibility = ["//example/web:__pkg__"],
    deps = [
        "//:node_modules/@tanstack/react-router",
        "//example/web/routes:main",
    ],
)
