load("@aspect_rules_ts//ts:defs.bzl", "ts_project")
load("@npm//:vite/package_json.bzl", vite_bin = "bin")

ts_project(
    name = "main",
    srcs = [
        "vite.config.ts",
    ],
    declaration = True,
    emit_declaration_only = True,
    tsconfig = "//:tsconfig",
    deps = [
        "//:node_modules/@tanstack/react-start",
        "//:node_modules/@vitejs/plugin-react",
        "//:node_modules/vite",
    ],
)

vite_bin.vite(
	name = "vite_build",
	srcs = [
		":main",
		"//example/web/router:main",
		"//example/web/routes:main",
	],
	out_dirs = ["dist"],
	args = ["build"],
	chdir = package_name(),
)
