load("@npm//:vite/package_json.bzl", vite_bin = "bin")
load("//:ts_library.bzl", "ts_library")

ts_library(
    name = "main",
    srcs = [
        "vite.config.ts",
    ],
    declaration = True,
    emit_declaration_only = True,
    tsconfig = "//:tsconfig",
    deps = [
        "//:node_modules/@tanstack/react-start",
        "//:node_modules/@vitejs/plugin-react",
        "//:node_modules/vite",
    ],
)

vite_bin.vite(
    name = "vite_build",
    srcs = [
        ":main",
        "//example/web/routes:main",
    ],
    args = ["build"],
    chdir = package_name(),
    out_dirs = ["dist"],
)
