load("@aspect_bazel_lib//lib:write_source_files.bzl", "write_source_files")
load("@aspect_rules_js//js:defs.bzl", "js_library")
load("@npm//:vite/package_json.bzl", vite_bin = "bin")

js_library(
    name = "main",
    srcs = [
        "vite.config.js",
    ],
    deps = [
        "//:node_modules/@tanstack/react-start",
        "//:node_modules/@vitejs/plugin-react",
        "//:node_modules/vite",
    ],
)

vite_bin.vite(
	name = "vite_build",
	srcs = [
		":main",
		":"
	],
)
