load("@aspect_rules_ts//ts:defs.bzl", "ts_project")

ts_project(
    name = "main",
    srcs = [
        "__root.tsx",
        "index.tsx",
    ],
    visibility = ["//example/web/route_tree:__pkg__"],
    deps = [
        "//:node_modules/@tanstack/react-router",
        "//:node_modules/@types/react",
        "//:node_modules/react",
    ],
)
