load("@aspect_bazel_lib//lib:directory_path.bzl", "directory_path")
load("@aspect_rules_js//js:defs.bzl", "js_binary")
load("@rules_typescript//npm:defs.bzl", "node_modules")

package(default_visibility = ["//visibility:public"])

node_modules(
    name = "node_modules",
    deps = [
        "@npm//:prettier",
    ],
)

directory_path(
    name = "prettier_entry",
    directory = ":node_modules",
    path = "prettier/bin/prettier.cjs",
)

js_binary(
    name = "prettier",
    entry_point = ":prettier_entry",
    env = {"BAZEL_BINDIR": "."},
)

alias(
    name = "oxfmt",
    actual = "@multitool//tools/oxfmt",
)
