name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  CiBuild:
    name: CI Build

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout self
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          bazelisk-version: 1.x
          disk-cache: ${{ github.workflow }}
          external-cache: |
            manifest:
              npm: package-lock.json
          repository-cache: true

      - name: Format check
        run: bazel run //:format.check

      - name: Test
        run: bazel test //...

      - name: Build
        run: bazel build //...
